version: '3'
services:
  db:
    image: mariadb:10.1
    volumes:
      - /docker/mission/mysql:/var/lib/mysql
    env_file: .env
    ports:
      - "3312:3306"
  web:
    image: ponkotuy/missionrecommender
    volumes:
      - .:/redloader
    env_file: .env_web
    ports:
      - "9047:9000"
    depends_on:
      - db
